-- Global libraries (user_id = null) that every account can read via the
-- "owner or global" select policies, but never write to directly.

insert into public.exercises (user_id, name, category, primary_muscle, equipment, is_custom) values
  (null, 'Barbell Back Squat', 'strength', 'Quadriceps', 'Barbell', false),
  (null, 'Barbell Bench Press', 'strength', 'Chest', 'Barbell', false),
  (null, 'Deadlift', 'strength', 'Back', 'Barbell', false),
  (null, 'Overhead Press', 'strength', 'Shoulders', 'Barbell', false),
  (null, 'Barbell Row', 'strength', 'Back', 'Barbell', false),
  (null, 'Pull Up', 'strength', 'Back', 'Bodyweight', false),
  (null, 'Chin Up', 'strength', 'Back', 'Bodyweight', false),
  (null, 'Dip', 'strength', 'Chest', 'Bodyweight', false),
  (null, 'Incline Dumbbell Press', 'strength', 'Chest', 'Dumbbell', false),
  (null, 'Dumbbell Shoulder Press', 'strength', 'Shoulders', 'Dumbbell', false),
  (null, 'Lateral Raise', 'strength', 'Shoulders', 'Dumbbell', false),
  (null, 'Barbell Curl', 'strength', 'Biceps', 'Barbell', false),
  (null, 'Hammer Curl', 'strength', 'Biceps', 'Dumbbell', false),
  (null, 'Triceps Pushdown', 'strength', 'Triceps', 'Cable', false),
  (null, 'Close-Grip Bench Press', 'strength', 'Triceps', 'Barbell', false),
  (null, 'Romanian Deadlift', 'strength', 'Hamstrings', 'Barbell', false),
  (null, 'Leg Press', 'strength', 'Quadriceps', 'Machine', false),
  (null, 'Leg Curl', 'strength', 'Hamstrings', 'Machine', false),
  (null, 'Leg Extension', 'strength', 'Quadriceps', 'Machine', false),
  (null, 'Hip Thrust', 'strength', 'Glutes', 'Barbell', false),
  (null, 'Walking Lunge', 'strength', 'Quadriceps', 'Dumbbell', false),
  (null, 'Standing Calf Raise', 'strength', 'Calves', 'Machine', false),
  (null, 'Lat Pulldown', 'strength', 'Back', 'Cable', false),
  (null, 'Seated Cable Row', 'strength', 'Back', 'Cable', false),
  (null, 'Face Pull', 'strength', 'Shoulders', 'Cable', false),
  (null, 'Plank', 'core', 'Abs', 'Bodyweight', false),
  (null, 'Hanging Leg Raise', 'core', 'Abs', 'Bodyweight', false),
  (null, 'Cable Crunch', 'core', 'Abs', 'Cable', false),
  (null, 'Treadmill Run', 'cardio', 'Cardio', 'Machine', false),
  (null, 'Rowing Machine', 'cardio', 'Cardio', 'Machine', false)
on conflict do nothing;

insert into public.compounds (user_id, name, category, default_unit, half_life_hours, is_custom) values
  (null, 'Testosterone Enanthate', 'anabolic_steroid', 'mg', 108, false),
  (null, 'Testosterone Cypionate', 'anabolic_steroid', 'mg', 120, false),
  (null, 'Testosterone Propionate', 'anabolic_steroid', 'mg', 20, false),
  (null, 'Nandrolone Decanoate', 'anabolic_steroid', 'mg', 144, false),
  (null, 'Boldenone Undecylenate', 'anabolic_steroid', 'mg', 336, false),
  (null, 'Trenbolone Acetate', 'anabolic_steroid', 'mg', 24, false),
  (null, 'Trenbolone Enanthate', 'anabolic_steroid', 'mg', 120, false),
  (null, 'Masteron Propionate', 'anabolic_steroid', 'mg', 20, false),
  (null, 'Anavar (Oxandrolone)', 'anabolic_steroid', 'mg', 9, false),
  (null, 'Dianabol (Methandrostenolone)', 'anabolic_steroid', 'mg', 5, false),
  (null, 'Winstrol (Stanozolol)', 'anabolic_steroid', 'mg', 9, false),
  (null, 'BPC-157', 'peptide', 'mcg', 4, false),
  (null, 'TB-500', 'peptide', 'mg', 48, false),
  (null, 'CJC-1295 (no DAC)', 'peptide', 'mcg', 0.5, false),
  (null, 'Ipamorelin', 'peptide', 'mcg', 2, false),
  (null, 'Sermorelin', 'peptide', 'mcg', 0.4, false),
  (null, 'Semaglutide', 'peptide', 'mg', 168, false),
  (null, 'HGH (Somatropin)', 'peptide', 'iu', 4, false),
  (null, 'HCG', 'ancillary', 'iu', 36, false),
  (null, 'Arimidex (Anastrozole)', 'ancillary', 'mg', 46, false),
  (null, 'Nolvadex (Tamoxifen)', 'ancillary', 'mg', 168, false),
  (null, 'Clomid (Clomifene)', 'ancillary', 'mg', 120, false),
  (null, 'Cabergoline', 'ancillary', 'mg', 68, false)
on conflict do nothing;

insert into public.foods (user_id, name, brand, serving_size, serving_unit, calories, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg, is_custom) values
  (null, 'Chicken Breast, cooked', null, 100, 'g', 165, 31, 0, 3.6, 0, 0, 74, false),
  (null, 'White Rice, cooked', null, 100, 'g', 130, 2.7, 28, 0.3, 0.4, 0.1, 1, false),
  (null, 'Rolled Oats, dry', null, 100, 'g', 389, 16.9, 66, 6.9, 10.6, 0, 2, false),
  (null, 'Whole Eggs', null, 50, 'g', 78, 6.3, 0.6, 5.3, 0, 0.6, 62, false),
  (null, 'Egg Whites', null, 100, 'g', 52, 11, 0.7, 0.2, 0, 0.7, 166, false),
  (null, 'Greek Yogurt, plain 0%', null, 100, 'g', 59, 10, 3.6, 0.4, 0, 3.2, 36, false),
  (null, 'Whey Protein Powder', null, 30, 'g', 120, 24, 3, 1.5, 0, 1, 50, false),
  (null, 'Broccoli, steamed', null, 100, 'g', 35, 2.4, 7.2, 0.4, 3.3, 1.4, 41, false),
  (null, 'Sweet Potato, baked', null, 100, 'g', 90, 2, 21, 0.1, 3.3, 6.5, 36, false),
  (null, 'Avocado', null, 100, 'g', 160, 2, 8.5, 14.7, 6.7, 0.7, 7, false),
  (null, 'Almonds', null, 30, 'g', 174, 6.4, 6.1, 15, 3.5, 1.2, 0, false),
  (null, 'Olive Oil', null, 15, 'ml', 119, 0, 0, 13.5, 0, 0, 0, false),
  (null, 'Salmon, cooked', null, 100, 'g', 208, 20, 0, 13, 0, 0, 59, false),
  (null, 'Lean Beef Mince 5%', null, 100, 'g', 137, 21, 0, 5, 0, 0, 66, false),
  (null, 'Banana', null, 118, 'g', 105, 1.3, 27, 0.4, 3.1, 14, 1, false)
on conflict do nothing;
